In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

## Iris sepal_width에 대한 회귀식 

In [3]:
from sklearn.datasets import load_iris
iris = load_iris()

In [4]:
columns = ['sepal_length','sepal_width','petal_length','petal_width']
irisDF = pd.DataFrame(iris.data, columns=columns)
irisDF['variety']=iris.target
irisDF.head(3)

sepal_length  sepal_width  petal_length  petal_width  variety
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0

In [7]:
y = irisDF['sepal_width'].values
y[:3]

array([3.5, 3. , 3.2])

In [8]:
del irisDF['sepal_width']

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = \
    train_test_split(irisDF, y, test_size=0.2, random_state=2020)

In [10]:
from sklearn.linear_model import LinearRegression
sim_lr = LinearRegression()

In [11]:
sim_lr.fit(x_train.values, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [12]:
y_pred = sim_lr.predict(x_test.values)

In [13]:
from sklearn.metrics import mean_squared_error
rmse = np.sqrt(mean_squared_error(y_test, y_pred))

In [14]:
rmse

0.2973029703087367

In [15]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.37084664236825526

In [16]:
sim_lr.coef_

array([ 0.60931348, -0.60769612,  0.65350473, -0.06958645])

In [17]:
sim_lr.intercept_

1.077679207902507

## 폐암 환자 생존율 예측

In [19]:
data_set = np.loadtxt("data/ThoraricSurgery.csv", delimiter=",")
data_set

array([[293.  ,   1.  ,   3.8 , ...,   0.  ,  62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88, ...,   0.  ,  60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19, ...,   0.  ,  66.  ,   1.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,  62.  ,   0.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,  58.  ,   1.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,  49.  ,   0.  ]])

In [23]:
X = data_set[:, :-1]
Y = data_set[:, -1]
X.shape, Y.shape

((470, 17), (470,))

In [24]:
x_train, x_test, y_train, y_test = \
    train_test_split(X, Y, test_size=0.2, random_state=2020)

In [26]:
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
svc = SVC()
svc.fit(x_train, y_train)
y_pred_svc = svc.predict(x_test)
accuracy_score(y_test, y_pred_svc)

0.851063829787234

In [27]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train, y_train)
y_pred_dtc = dtc.predict(x_test)
accuracy_score(y_test, y_pred_dtc)

0.7978723404255319

In [29]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train, y_train)
y_pred_lr = lr.predict(x_test)
accuracy_score(y_test, y_pred_lr)

0.851063829787234

## 미드웨이 영화 리뷰 감성 분석

In [34]:
midway = pd.read_csv('./data/midway.tsv', sep='\t')

In [35]:
midway.head(3)

Unnamed: 0  평점                일시                           감상평
0           0   9  2019.12.31 09:48    미드웨이가 재밌으면 추천 백두산이 재밌으면 비추
1           1  10  2019.12.31 10:41     저 해전이 있었기에 우리나라 광복도 가능 했음
2           2  10  2019.12.31 09:38  백두산 상영관 대폭줄이고 미드웨이 상영관 대폭늘려라

In [36]:
midway['평점'].value_counts()

10    3071
8      513
9      468
6      216
7      169
1      107
4       97
2       90
5       68
3       26
Name: 평점, dtype: int64