# Numpy 연습문제

In [1]:
import numpy as np

In [2]:
# 1. 길이가 10인 0-벡터를 만드세요.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
# 2. 길이가 10이며 다섯번째 원소만 1이고 나머지 원소는 모두 0인 벡터를 만드세요.
np.eye(1, 10, k=4)

array([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [4]:
np.where(np.arange(10)==4, 1, 0)

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [5]:
# 3. 10 부터 49까지의 값을 가지는 벡터를 만드세요.
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [6]:
# 4. 위(3번) 벡터의 순서를 바꾸세요.
np.arange(49, 9, -1)

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [7]:
# 5. 0부터 8까지의 값을 가지는 3x3 행렬을 만드세요.
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
# 6. 벡터 [1,2,0,0,4,0] 에서 원소의 값이 0이 아닌 원소만 선택한 벡터를 만드세요.
a = np.array([1,2,0,0,4,0], int) 
a[a != 0]

array([1, 2, 4])

In [9]:
# 7. 3x3 단위 행렬(identity matrix)을 만드세요.
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# 8. 난수 원소를 가지는 3x3 행렬을 만드세요
np.random.seed(604)
a = np.random.random(9).reshape(3, 3)
a

array([[0.29199497, 0.16131679, 0.6353873 ],
       [0.17588539, 0.10216827, 0.59007575],
       [0.79085085, 0.97099855, 0.31192678]])

In [15]:
# 9. 위(8번)에서 만든 난수 행렬에서 최대값/최소값 원소를 찾으세요. (값)
a[np.argmax(a)//3, np.argmax(a)%3], np.argmax(a)

(0.9709985452208039, 7)

In [16]:
a[np.argmin(a)//3, np.argmin(a)%3], np.argmin(a)

(0.10216826983588667, 4)

In [17]:
# 10. 위(8번)에서 만든 난수 행렬에서 행 평균, 열 평균을 계산하세요.
np.mean(a, axis = 1), np.mean(a, axis = 0)

(array([0.36289969, 0.28937647, 0.69125872]),
 array([0.41957707, 0.41149454, 0.51246328]))